import type { Metadata } from "next";
import { Source_Code_Pro, Open_Sans, Audiowide } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header.component";
import { ReactNode } from "react";

const getRoboto = Source_Code_Pro({
	variable: "--font-roboto",
	weight: ["300", "400", "500", "700", "900"],
	subsets: ["latin"],
});

const getOpenSans = Open_Sans({
	variable: "--font-body",
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin"],
});

const getAudiowide = Audiowide({
	variable: "--font-headers",
	weight: ["400"],
	subsets: ["latin"],
});


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en" >
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@400;500;600;700&family=Material+Symbols+Rounded:wght@400;500;600;700&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body className={`${getRoboto.variable} ${getOpenSans.variable} ${getAudiowide.variable}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
